#spring.application.name=jdbcspring
# spring.datasource.url=jdbc:postgresql://localhost:5432/demo
# spring.datasource.username=postgres
# spring.datasource.password=pawat7452
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.sql.init.mode=never
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
#spring.datasource.platform=postgres


import com.cloudinary.Cloudinary;
import com.cloudinary.utils.ObjectUtils;

Cloudinary cloudinary = new Cloudinary(ObjectUtils.asMap(
    "cloud_name", "",
    "api_key", "",
    "api_secret", ""
)
);